---
# tasks file for adrianjuhl.yq

- name: Get stats of installed yq file
  ansible.builtin.stat:
    path: "{{ adrianjuhl__yq__install_bin_directory }}/yq"
    checksum_algorithm: sha512
  register: yq_file_stat
  become: false

- name: Install yq if missing or invalid
  ansible.builtin.include_tasks: install_yq.yml
  when: not yq_file_stat.stat.exists

