---
- name: Install yq
  hosts: localhost
  tasks:
    - name: Install yq
      ansible.builtin.include_role:
        name: adrianjuhl.yq
        apply:
          become: "{{ local_playbook__install_yq__requires_become }}"
